---
- hosts: all
  become: yes
  tasks:
    - include_tasks: - /home/nikhil/devopsdata/createfilebook.yml

    - name: install apache2 on node server
      apt:
          name: apache2
          state: present