---
- hosts: all
  become: yes
  tasks:
    - include_tasks: createfilebook.yml

    - name: install apache2 on node server
      apt:
          name: apache2
          state: present
          notify: restart

    - name: i want to replace apache default page
      template:
          src: newtemplatefile.j2
          dest: /var/www/html/index.html