---
    - name: Install OpenJDK 8 on Ubuntu
      apt:
        name: "{{ ubuntujavapckg }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install OpenJDK 8 on Red Hat
      yum:
        name: "{{ redhatjavapckg }}"
        state: present
      when: ansible_os_family == "RedHat"
